# Generated by Django 5.0.1 on 2024-06-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(null=True, upload_to='images/courses/'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='trainer_name',
            field=models.CharField(default='Achsa Jomesh', max_length=100),
        ),
    ]
