# Generated by Django 5.0.1 on 2024-06-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0005_rename_video_coursevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LISTENING', 'Listening'), ('SPEAKING', 'Speaking'), ('READING', 'Reading'), ('WRITING', 'Writing')], max_length=50, unique=True)),
                ('description', models.TextField(default='Default description')),
                ('author_name', models.CharField(default='Achsa Jomesh', max_length=100)),
                ('course_image', models.ImageField(null=True, upload_to='images/courses/')),
            ],
        ),
    ]
