# Generated by Django 5.0.1 on 2024-06-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0006_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='course_image',
            new_name='skill_image',
        ),
    ]
