# Generated by Django 5.0.1 on 2024-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0007_rename_course_image_skills_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='price',
            field=models.CharField(default=499, max_length=10),
        ),
    ]
